mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponseRedirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('accounts/', include('allauth.urls')),
    path('upload/', include('upload.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', lambda request: HttpResponseRedirect('/polls/')),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    #path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),

    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    #path('specifics/<int:question_id>/', views.detail, name='detail'),   # esimerkki polusta: specifics/-polku
    # ex: /polls/5/results/
    #path('<int:question_id>/results/', views.results, name='results'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),

    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),

    # ex: /polls/1/comment/  # äänestysnumerokohtainen kommentin jättäminen
    path('<int:question_id>/comments/', views.leave_comment, name='leave_comment'),
    path('<int:question_id>/comment_thank_you/', views.comment_thanks, name='comment_thanks'),
    path('fetch_homepage/<int:comment_id>/', views.go_to_homepage, name='fetch_homepage'),

    path('search/', views.search, name='polls_search'),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
#from django_bleach.models import BleachField


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text


class Comment(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.TextField()   # here (together with comment_thank_you.html) is a vulnerability for XSS-injection
    # text = BleachField()          # this fix bleaches (sanitizes) end-user's input before it is taken to the database
    name = models.CharField(max_length=30, blank=True, null=True)
    email = models.EmailField(blank=False, null=True)  # blank=False => email is mandated; it is representing "sensitive information" in this exercise)
    created_at = models.DateTimeField(auto_now_add=True)
    url = models.CharField(max_length=100, blank=True, null=True)

    

polls/forms.py
from django import forms


from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text', 'name', 'email', 'url']
        labels = {
            'text': 'Your comment',
            'name': 'Name (optional)',
            'email': 'Email (mandatory, will not be shown)',
            'url': 'Homepage (optional)',
        }

#class UploadPoll(forms.Form):
#    new_poll = forms.FrileField()

polls/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice, Comment
from django.template import loader  # obsolete, not needed after 'shorcut' used
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
#from django_comments.forms import CommentForm
#from django_comments.models import Comment
from .forms import CommentForm
import requests
from django.db.models import Q
from django.db.models import Count 
from django.db import connection


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        #"""Return the last five published questions."""
        #return Question.objects.order_by('-pub_date')[:5]

        most_popular_poll = Question.objects.annotate(num_votes=Count('choice')).order_by('-num_votes')[:2]
        return most_popular_poll


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):

    # changed the service to "anybody can vote"
    # if not request.user.is_authenticated:           # this fixes the tampering of detail.html user authentication (mimt-attack against incomplete user authentication)
    #    return HttpResponseForbidden("You must be logged in to vote !")

    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
    
def leave_comment(request, question_id):

    question = get_object_or_404(Question, pk=question_id)
    #print("Kysymyksen id on:", question_id)
    #print("Form data on:", request.POST)
    comments = Comment.objects.filter(question=question).order_by('-created_at')
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.question = question
            comment.save()
            return HttpResponseRedirect(reverse('polls:comment_thanks', args=(question.id,)))
    else:
        form = CommentForm()

    return render(request, 'polls/comment_leave_comment.html', {'question': question, 'comments': comments, 'form': form})


def comment_thanks(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
        comments = Comment.objects.filter(question=question).order_by('-created_at')
    except Question.DoesNotExist:
        raise Http404("Question does not exist")

    return render(request, 'polls/comment_thank_you.html', {
        'question': question,
        'comments': comments
    })

def go_to_homepage(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)

    try:
        response = requests.get(comment.url)
        content = response.text
        print('kommentin url', comment.url)
        #print('content', content)
    except requests.RequestException as e:
        return HttpResponse(f"An error occurred: {e}")

    return render(request, 'polls/comment_show_homepage.html', {'name': comment.name, 'url': comment.url, 'content': content})

def search(request):
    query = request.GET.get('q')
    if query:
        questions = Question.objects.filter(
            Q(question_text__icontains=query) |      # Hae kysymyksiä ja
            Q(choice__choice_text__icontains=query)  # vaihtoehtoja
        ).distinct()                                 # Poistaatuplat

    else:
        questions = Question.objects.all()

    return render(request, 'polls/polls_search.html', {'questions': questions, 'query': query})








""" MUISTISSA ITSELLE; ALLA OLEVA EI LÄHDE TOIMIMAAN haluamallani tavalla (liittyy SQL-injectioniin)

def search(request):
    query = request.GET.get('q', '')
    print('query', query)
    if query:
        sql_query = 
            SELECT * 
            FROM polls_question 
            WHERE question_text LIKE ?
        
        with connection.cursor() as cursor:
            cursor.execute(sql_query, [f'%{query}%'])
            questions = cursor.fetchall()
        print('questions', questions)
    else:
        questions = Question.objects.all()
        print('questions', questions)

    return render(request, 'polls/polls_search.html', {'questions': questions, 'query': query})


"""

polls/templates/polls/comment_leave_comment.html
<!DOCTYPE html>
<html>
<head>
    <title>Leave a Comment</title>
</head>
<body>
    <h1>Leave your comment about <FONT COLOR="#008000">"{{ question.question_text }}"</FONT> here</h1>
    
    <form method="post" action="{% url 'polls:leave_comment' question.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>

    <p>No worries, your email will not be shown to others!</p> <!-- Jeah right... tämä on harjoitustehtävä ja tarkoituksella bugiseksi tehty... -->

    <br/>
    <a href="{% url 'polls:index' %}">Back to polls</a>
</body>
</html>

polls/templates/polls/comment_show_homepage.html
<!DOCTYPE html>
<html>
<head>
    <title>Fetched URL</title>
</head>
<body>
    <h2>Fetched Homepage {{ url }} of user {{ name }}</h2>
    <iframe src="{{ url|safe }}" style="width:100%; height:500px;"></iframe>
    <br/>
    <a href="{% url 'polls:index' %}">Back to polls</a>
</body>
</html>

polls/templates/polls/comment_thank_you.html
<!DOCTYPE html>
<html>
<head>
    <title>Thank you</title>
</head>
<body>
    <h2>Thank you for your comment. Every opinion counts!</h2>
    <br/>
    <a href="{% url 'polls:index' %}">Back to polls</a>

    <h3>Comments about <FONT COLOR="#008000">"{{ question.question_text }}"</FONT>:</h3>

    <ul>
        {% for comment in comments %}

        <!-- Row 19 below has XSS-vulnerability, because comment.text is treated as "safe", although XSS-injection may have (and has) happned elsewhere-->
        <!-- BUT fixing frontend is not enough, so real fix is in polls/models.py, see class Comment and BleachField() rows 26-27-->
        <li>({{ comment.created_at }}) {% if comment.name %} comment by <b>{{ comment.name }}</b> {% else %} comment by <b>anonymous</b> {% endif %}: {{ comment.text|safe }}  {% if comment.url %} <b>Homepage:</b> <a href="{% url 'polls:fetch_homepage' comment.id %}"> {{ comment.url }}</a> {% endif %}</li>
        <li style="display: none">Id: {{ comment.id }} ({{ comment.created_at }}): {{ comment.text|safe }} ({% if comment.name %} Name: {{ comment.name }} ) Email: {{ comment.email }} Homepage: <a href="{% url 'polls:fetch_homepage' comment.id %}">{{ comment.url }}</a> {% else %} anonymous {% endif %}<li>

        <script>var email = "{{ comment.email }}"; console.log("email: " +email)</script>
            {% empty %}
            <li>No comments yet.</li>
        {% endfor %}
    </ul>
</body>
</html>

polls/templates/polls/detail.html
<h1>Poll #{{ question.id }}: {{ question.question_text }}</h1>

{# {% if user.is_authenticated %} #} <!-- muistiin itselle: django-templaten kommentointi ei estä kaarisulkujen sisällön suorittamista, siksi vaatii eri tägäyksen -->

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}  <!-- csrf_tokenin lisäämällä estyy laiton äänestäminen (kun settings.py:ssä on django.middleware.csrf.CsrfViewMiddleware)-->
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    </br>
    <input type="submit" value="Vote">
    </form>

{#  {% else %} #}  <!-- sama tägijuttu täällä (kuin ylimpänä) -->
<!-- <br/>
    <p>Only registered users can vote. You need to sign in before you can vote.</p>
    <a href="{% url 'account_login' %}">Sign in</a>
    <br/>
-->
{#    {% endif %} #}

<br/>
<a href="{% url 'polls:index' %}">Cancel and go back to polls</a>

polls/templates/polls/index.html
<h1>Select your poll</h1>

Popular polls currently:
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% if user.is_authenticated %}
    <a href="http://127.0.0.1:8000/upload">Upload your own new poll</a>
    <br>
    <a href="http://127.0.0.1:8000/accounts/logout">Sign out</a>
{% else %}
    <a href="http://127.0.0.1:8000/accounts/login">Sign in</a>
{% endif %}

<iframe src="http://127.0.0.1:8000/polls/search/" width="100%" height="100%"></iframe>

polls/templates/polls/polls_search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search Polls</title>
</head>
<body>
    <h2>Search for Polls</h2>

    <form method="GET">
        <input type="text" name="q" placeholder="Search word or phrase...">
        <button type="submit">Search</button>
    </form>
    {% if query %}
        <h2>Resulting polls for "{{ query }}"</h2>
    {% endif %}
    <ul>
        {% for question in questions %}
            <li>
                <h3><a href="{% url 'polls:detail' question.id %}" target="_top">{{ question.question_text }}</a></h3>
                <ul>
                    {% for choice in question.choice_set.all %}
                        <li>{{ choice.choice_text }}</li>
                    {% endfor %}
                </ul>
            </li>
        {% empty %}
            <li>No results found.</li>
        {% endfor %}
    </ul>
</body>
</html>

polls/templates/polls/results.html
<h1>Results of Poll #{{ question.id }}: {{ question.question_text }}</h1>
Current status of poll in order of votes:
<ul>
{% for choice in question.choice_set.all|dictsortreversed:"votes" %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

</br>
<a href="{% url 'polls:leave_comment' question.id %}">Want to leave a comment?</a>
</br>
</br>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
<br/>
<br/>
<a href="{% url 'polls:index' %}">Back to polls</a>